name: chat_novel
description: 交互式AI小说生成应用
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.3.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.14
  google_fonts: ^4.0.3
  flutter_spinkit: ^5.2.0
  langchain: ^0.0.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 